#!/bin/sh

# Create the vendor link since it isn't persisted through the docker build.
vendor_dir=/var/www/html/vendor;
if [ ! -f "$vendor_dir" ]; then
    ln -s /usr/local/lib/php/akeneo/vendor $vendor_dir;
fi;

# Finally call the PHP entrypoint with whatever was passed to us.
/usr/local/bin/entrypoint $@
