#!/bin/sh

# Create the vendor link since it isn't persisted through the docker build.
ln -s /usr/local/lib/php/akeneo/vendor /var/www/html/vendor;

# Finally call the PHP entrypoint with whatever was passed to us.
/usr/local/bin/entrypoint $@
